language: python
branches:
  only:
  - master
  - dev
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
install:
  - pip install -r requirements/dev.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q pyecharts~=1.9
  - python setup.py install
script:
  - nosetests tests
  - python example/manage.py test --noinput
  - flake8 django_echarts tests example --ignore=E501 --max-complexity 10