language: python
branches:
  only:
  - master
  - dev
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
install:
  - pip install -r requirements/dev.txt
  - python setup.py install
script:
  - nosetests tests
  - python example/manage.py test --noinput
  - flake8 django_echarts tests example --ignore=E501 --max-complexity 10