site_name: django-echarts
theme:
  icon:
    logo: material/monitor-dashboard
  name: material
  features:
    - navigation.tabs
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - 快速开始: index.md
  - 可视化构建:
    - 使用教程: starter/base.md
    - 组件和布局: starter/widget_and_layout.md
    - UI框架和主题: starter/themes.md
    - 依赖项和静态文件: guides/dms.md
    - 高级开发: guides/advance_development.md
  - 参考:
    - 项目设置: reference/configure.md
    - 视图和模板: reference/api.md
    - 模板标签库: reference/tags.md
    - 命令行工具: reference/commands.md
  - Gallery: gallery.md
  - 项目开发:
    - 更新日志: changelog.md
    - 关于项目: about.md
    - 发布日志:
      - v0.5.0: release-note/v050.md