site_name: django-echarts
theme:
  icon:
    logo: material/monitor-dashboard
  name: material
  features:
    - navigation.tabs
    - navigation.sections
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - 快速开始: index.md
  - 可视化构建:
    - 基本功能:
      - 功能设置: starter/base.md
      - 图表合辑及其布局: starter/layout.md
      - UI框架和主题: starter/themes.md
      - 高级开发: guides/advance_development.md
    - 参考:
      - 视图和模板: reference/api.md
      - 模板标签库: reference/tags.md
      - 命令行工具: reference/commands.md
  - 图表构建:
    - pyecharts图表开发: guides/charts.md
    - 依赖项和静态文件: guides/dms.md
    - 配置: guides/configure.md
  - Gallery: gallery.md
  - 项目开发:
    - 更新日志: changelog.md
    - 关于项目: about.md
    - 发布日志:
      - v0.5.0: release-note/v050.md