name: unittest
on:
  push:
    branches:
      - master
      - dev
      - 'release/**'
  pull_request:
    branches:
      - master
jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9' ]
        django-version: [ '2.2', '3.2' ]
        pyecharts-version: ['1.9.1', '2.0.2']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django~=${{ matrix.django-version }}
          pip install borax~=4.0
          pip install pyecharts~=${{ matrix.pyecharts-version }}
          pip install typing_extensions~=4.5
          pip install htmlgenerator~=1.2
          pip install flake8~=3.9
          pip install nose2~=0.10
      - name: Lint with flake8
        run: |
          flake8 django_echarts tests
      - name: Test with pytest
        run: |
          nose2 --with-coverage --coverage django_echarts --coverage-report xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true